FROM debian:stretch
RUN apt-get update && \
       apt-get install -y git awscli wget gnupg gnupg2 zip unzip curl apt-transport-https software-properties-common python-software-properties && \
       useradd -ms /bin/bash mvp
